// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortnerApi.Services;

#nullable disable

namespace UrlShortnerApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806163326_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortnerApi.Url", b =>
                {
                    b.Property<string>("ShortUrl")
                        .HasColumnType("text");

                    b.HasKey("ShortUrl");

                    b.ToTable("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
